### ISSUE TITLE
Replace uses of Ref with StateT instead

### ISSUE THREAD

**Issue by cprussin** [citizennet/purescript-httpure#120]
Our `Ref` uses (`Body.read` and `TestHelpers.toBuffer`) could and should be more safely written using `StateT` instead.

**Comment by akheron** [comment]
I don't think this is possible at least with the callback based approach in the places where `Ref` is currently used. I'm not sure if it would be possible to use `Aff`, and would `StateT` be applicable then.

**Comment by citizengabe** [comment]
Closing for now. If someone encounters a problem that this could solve we can revisit.

**Comment by citizengabe** [comment]
Closing for now. If someone encounters a problem that this could solve we can revisit.
