### ISSUE TITLE
Remove `newtype` for `Headers`

### ISSUE THREAD

**Issue by cprussin** [citizennet/purescript-httpure#139]
`Headers` was originally written as a newtype so that it could have a case insensitive `Lookup` instance without clashing with the default `Object` instance.  But since #138 changed `Headers` to a `Map CaseInsensitiveString String`, there's no real value of the newtype any more other than custom `Show` and `Semigroup` instances.  The `Show` instance could be replaced with another function name since it's not even purescript convention anyways, and the `Semigroup` instance is likely redundant at this point.

We should look into getting rid of the newtype and just make `Headers` a type synonym instead.

**Comment by citizengabe** [comment]
Closing since this would be a breaking change. Also, any change to the underlying implementation would also be breaking in the future.
