### ISSUE TITLE
PureScript 0.15-compatible release.

### ISSUE THREAD

**Issue by thomashoneyman** [citizennet/purescript-httpure#196]
`httpure` is now compatible with PureScript 0.15 via the changes in #194. I'd love to get `httpure` updated in the package sets, but that requires a new release of the library (0.15.0, I suppose). Is there anything waiting to be done before a release can be made? cc: @cprussin, @davezuch

**Comment by cprussin** [comment]
@thomashoneyman apologies, [v0.15.0](https://github.com/citizennet/purescript-httpure/releases/tag/v0.15.0) has been tagged

**Comment by cprussin** [comment]
also, can we just comment on how cool it is that the httpure v0.15.0 release is the one that aligns with purescript v0.15?

**Comment by davezuch** [comment]
Lol I noticed that too.
